### ISSUE TITLE
How to sort list based on PID in lxtask using directive .conf

### ISSUE THREAD

**Issue by andriawan** [trizen/config-files#1]
i wonder to get list of running process in lxtask based on PID (from 1 up to newest process) when it is started. it seems there is no certain directive to get it. show me your opinions. of course we can get it just clicking the header tab of PID. but i wanna make it default when it is started

**Comment by trizen** [comment]
By looking at the source-code of lxtask, the only supported config options, are:

* show_user_tasks
* show_root_tasks
* show_other_tasks
* show_full_path
* show_cached_as_free
* full_view
* win_width
* win_height
* refresh_interval

This can be checked starting at line 230 in https://searchcode.com/codesearch/view/21949017/

Please consider sending this as a feature-request to the developer of lxtask and he might add an option for this in the future.
